export const contact = {
  title: "Contact — EMFI",
  eyebrow: "Contact",
  headline: "Discuss your\nrequirements.",
  body: "Keep it simple. London for UK operations. Dubai for EMFI Capital (DIFC). Cayman Islands for EMFI Fund and Cayman-related matters.",
  formEyebrow: "Institutional enquiry",
  fields: ["Full name", "Firm name", "Role / title", "Email", "Phone (optional)"],
  clientType: "Client type",
  clientTypes: [
    "Financial Institution",
    "Asset Manager",
    "Wealth Manager",
    "Other Professional",
  ],
  serviceInterest: "Service interest",
  services: [
    "Research & Execution",
    "Settlement & Custody",
    "Wealth & Asset Management",
    "EMFI Fund / Cayman",
    "General",
  ],
  message: "Message",
  confirm:
    "I confirm I am a Professional Client or Eligible Counterparty",
  submit: "Send enquiry",
  success: "Enquiry received. Our team will respond shortly.",
  locationsEyebrow: "Locations",
  locations: [
    {
      city: "London",
      entity: "UK operations and relevant regulated entities",
      note: "Authorised and regulated by the FCA",
      kind: "office" as const,
      lines: [
        "25-26 Dering Street, Third Floor",
        "Mayfair, London W1S 1AW",
        "United Kingdom",
      ],
      email: "contact@emfi.uk",
    },
    {
      city: "Dubai",
      entity: "EMFI Capital (DIFC) Limited",
      note: "DFSA authorised · F011663",
      kind: "office" as const,
      lines: [
        "IH-00-01-02-OF-01, Level 2",
        "Innovation One, DIFC",
        "Dubai, UAE",
      ],
      email: "contact@emfi.ae",
    },
    {
      city: "Cayman Islands",
      entity: "EMFI Fund",
      note: "Enquiries relating to EMFI Fund and Cayman-related matters. Not an EMFI office.",
      kind: "enquiry" as const,
      lines: [] as string[],
      email: "contact@emfi.uk",
    },
  ],
  coverage: "Operations coverage across London and Dubai time zones.",
};
